apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp  # Name for the AMQP port (5672)
      port: 5672
      targetPort: 5672
      protocol: TCP
    - name: management  # Name for the management UI port (15672)
      port: 15672
      targetPort: 15672
      protocol: TCP
  type: ClusterIP  # Ensure that you set this to ClusterIP if you're routing through ingress

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          ports:
            - containerPort: 5672
            - containerPort: 15672
