apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-execution-worker
spec:
  replicas: 3  # Number of worker pods
  selector:
    matchLabels:
      app: code-execution-worker
  template:
    metadata:
      labels:
        app: code-execution-worker
    spec:
      containers:
        - name: worker
          image: ammyy9908/python-worker:latest  # Replace with your Docker image
          env:
            - name: RABBITMQ_URL
              value: "amqp://guest:guest@rabbitmq-service:5672/"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
